import 'package:tms_sathi/page/home/role/enum/role_enum.dart';

import '../../../../navigations/navigation.dart';


class RoutePermission{
  static final Map<UserRole, List<String>> roleRoutes = {
  UserRole.Admin: [
    // Admin has access to all routes
    AppRoutes.splash,
    AppRoutes.homeScreen,
    AppRoutes.signUp,
    AppRoutes.editProfile,
    AppRoutes.login,
    AppRoutes.fsrScreen,
    AppRoutes.attendanceScreen,
    AppRoutes.otpScreen,
    AppRoutes.calendarScreen,
    AppRoutes.expenditureScreen,
    AppRoutes.serviceReqScreen,
    AppRoutes.amcScreen,
    AppRoutes.agentsScreen,
    AppRoutes.mapView,
    AppRoutes.uploadDocumenth,
    AppRoutes.ticketListScreen,
    AppRoutes.addfsrScreen,
    AppRoutes.leaveReportScreen,
    AppRoutes.createamcScreen,
    AppRoutes.calenderViewScreen,
    AppRoutes.customerListScreen,
    AppRoutes.principleCustomerScreen,
    AppRoutes.leadListScreen,
    AppRoutes.leadFormFieldScreen,
    AppRoutes.serviceCategoriesScreen,
    AppRoutes.SuperAgentsScreen,
    AppRoutes.accountViewScreen,
    AppRoutes.technicianListsScreen,
    AppRoutes.addtechnicianListScreen,
    AppRoutes.notificationsScreen,
    AppRoutes.ticketListCreationScreen,
    AppRoutes.leaveUpdateScreen,
    AppRoutes.addAmcCallenderScreen,
    AppRoutes.pricingScreenView,
    AppRoutes.addSuperuserViewScreen,
    AppRoutes.showViewAllDataAttendanceScreen,
  ],

  UserRole.SuperUser: [
    // SuperUser has access to most routes except admin-specific ones
    AppRoutes.splash,
    AppRoutes.homeScreen,
    AppRoutes.editProfile,
    AppRoutes.login,
    AppRoutes.fsrScreen,
    AppRoutes.attendanceScreen,
    AppRoutes.otpScreen,
    AppRoutes.calendarScreen,
    AppRoutes.expenditureScreen,
    AppRoutes.serviceReqScreen,
    AppRoutes.amcScreen,
    AppRoutes.agentsScreen,
    AppRoutes.mapView,
    AppRoutes.uploadDocumenth,
    AppRoutes.ticketListScreen,
    AppRoutes.addfsrScreen,
    AppRoutes.leaveReportScreen,
    AppRoutes.createamcScreen,
    AppRoutes.calenderViewScreen,
    AppRoutes.customerListScreen,
    AppRoutes.leadListScreen,
    AppRoutes.leadFormFieldScreen,
    AppRoutes.serviceCategoriesScreen,
    AppRoutes.technicianListsScreen,
    AppRoutes.notificationsScreen,
    AppRoutes.ticketListCreationScreen,
    AppRoutes.leaveUpdateScreen,
    AppRoutes.addAmcCallenderScreen,
  ],

  UserRole.Agent: [
    // Agent has access to basic operations and their specific screens
    AppRoutes.splash,
    AppRoutes.homeScreen,
    AppRoutes.editProfile,
    AppRoutes.login,
    AppRoutes.fsrScreen,
    AppRoutes.attendanceScreen,
    AppRoutes.otpScreen,
    AppRoutes.calendarScreen,
    AppRoutes.expenditureScreen,
    AppRoutes.serviceReqScreen,
    AppRoutes.ticketListScreen,
    AppRoutes.addfsrScreen,
    AppRoutes.leaveReportScreen,
    AppRoutes.calenderViewScreen,
    AppRoutes.customerListScreen,
    AppRoutes.notificationsScreen,
    AppRoutes.leaveUpdateScreen,
  ],

  UserRole.Technician: [
    // Technician has access to basic and technical operations
    AppRoutes.splash,
    AppRoutes.homeScreen,
    AppRoutes.editProfile,
    AppRoutes.login,
    AppRoutes.fsrScreen,
    AppRoutes.attendanceScreen,
    AppRoutes.otpScreen,
    AppRoutes.serviceReqScreen,
    AppRoutes.ticketListScreen,
    AppRoutes.addfsrScreen,
    AppRoutes.leaveReportScreen,
    AppRoutes.notificationsScreen,
    AppRoutes.leaveUpdateScreen,
  ],
};}
