import 'dart:io';
import 'dart:typed_data';
import 'package:dio/dio.dart' as dioo;

import '../../../response_models/add_sales_response_model.dart';
import '../../../response_models/add_technician_response_model.dart';
import '../../../response_models/agents_response_model.dart';
import '../../../response_models/amcData_customerWise_response_model.dart';
import '../../../response_models/amc_response_model.dart';
import '../../../response_models/attendance_response_model.dart';
import '../../../response_models/check_points_response_model.dart';
import '../../../response_models/customerBrand_response_model.dart';
import '../../../response_models/customer_list_response_model.dart';
import '../../../response_models/customer_rating_response_model.dart';
import '../../../response_models/expenses_response_model.dart';
import '../../../response_models/export_ticket_models.dart';
import '../../../response_models/fsr_response_model.dart';
import '../../../response_models/holidays_calender_response_model.dart';
import '../../../response_models/interaction_leads_response_model.dart';
import '../../../response_models/lead_response_model.dart';
import '../../../response_models/lead_satus_response_model.dart';
import '../../../response_models/lead_source_type_response_model.dart';
import '../../../response_models/leave_allocation_response_model.dart';
import '../../../response_models/leave_response_model.dart';
import '../../../response_models/leaves_history_response_model.dart';
import '../../../response_models/leaves_response_model.dart';
import '../../../response_models/login_response_model.dart';
import '../../../response_models/otp_response_model.dart';
import '../../../response_models/post_amc_response_model.dart';
import '../../../response_models/register_response_model.dart';
import '../../../response_models/resend_otp_api_call.dart';
import '../../../response_models/sales_response_model.dart';
import '../../../response_models/service_requests_response_model.dart';
import '../../../response_models/services_all_response_model.dart';
import '../../../response_models/services_response_model.dart';
import '../../../response_models/sub_service_by_subServiceId_response_model.dart';
import '../../../response_models/sub_service_response_model.dart';
import '../../../response_models/super_user_response_model.dart';
import '../../../response_models/technician_response_model.dart';
import '../../../response_models/ticket_history_response_model.dart';
import '../../../response_models/ticket_response_model.dart';
import '../../../response_models/today_ticket_response_model.dart';
import '../../../response_models/user_leaves_Data_response_model.dart';
import '../../../response_models/user_response_model.dart';

abstract class AuthenticationApi {
  Future<LoginResponseModel> loginApiCall({Map<String, dynamic>? dataBody});

  Future<RegisterResponseModel> registerApiCall(
      {Map<String, dynamic>? dataBody});

  Future<ResendOtpResponseModel> resendOtpApiCall({Map<String, dynamic>? dataBody});
  Future<OtpResponseModel> verifyOtpApiCall({Map<String, dynamic>? dataBody});
  Future<UserResponseModel>userDetailsApiCall({Map<String, dynamic>? dataBody, String? id});
  Future<UserResponseModel>updateUserDetailsApiCall({Map<String, dynamic>? dataBody, String? id});
  Future<UserResponseModel> userProfileImageUpdateApiCall(File imageFile);
  Future<HolidayResponseModel>holidaysCalenderApiCall({Map<String, dynamic>? dataBody});
  Future<PutHolidayResponseModel> postholidaysCalenderApiCall({Map<String, dynamic>? dataBody});
  Future<PutHolidayResponseModel> putholidaysCalenderApiCall({Map<String, dynamic>? dataBody, required String id});
  Future<PutHolidayResponseModel> deleteholidaysCalenderApiCall({Map<String, dynamic>? dataBody, required String id});
  // Future<List<TicketResponseModel>>getticketDetailsApiCall({Map<String, dynamic>? dataBody});
  Future<TicketResponseModel>getticketDetailsApiCall({Map<String, dynamic>? dataBody});
  Future<deleteTicketDataResponseModel>deleteticketDetailsApiCall({Map<String, dynamic>? dataBody,String? id});
  Future<List<TicketHistoryResponseModel>>getTicketHistoryData({Map<String, dynamic>?dataBody,required String id });
  Future<TicketResponseModel>postTicketDetailsApiCall({Map<String, dynamic>? dataBody});
  Future<List<CustomerBrandResponseModel>> getCustomerBrandDetailsApiCall({Map<String, dynamic>? dataBody, String? id});
  Future<List<BrandAmcNameResponseModel>> getBrandAmcNameDetailsApiCall(
      {Map<String, dynamic>? dataBody, String? id});
  Future<List<FsrCategoriesNameResponseModel>> getfsrCategoriesDetailsApiCall(
      {Map<String, dynamic>? dataBody, String? id});
  Future<LeaveResponseModel>getLeavesApiCall({Map<String, dynamic>? dataBody});
  Future<LeavePostResponseModel>postLeavesApiCall({Map<String, dynamic>?dataBody});
  Future<LeaveResponseModel>putLeavesApiCall({Map<String, dynamic>? dataBody,id});
  Future<List<LeavesHistoryViewResponseModel>>getLeaveHistoryData({Map<String, dynamic>?dataBody,required String id });
  Future<SuperUsersResponseModel>getSuperUserApiCall({Map<String, dynamic>? dataBody});
  Future<SuperUsersResponseModel> postSuperUserApiCall({Map<String, dynamic>?dataBody});
  Future<AddTechnicianResponseModel>addTechnicialPostApiCall({Map<String, dynamic>? dataBody, parameters});
  Future<TechnicianResponseModel>getTechnicianDetailsApiCall({Map<String, dynamic>? dataBody, parameters});
  Future<List<AttendanceUserResponseModel>>getCalenderViewUserAttendanceApiCall({Map<String, dynamic>? dataBody, parameter});
  Future<FsrResponseModel>getfsrDetailsApiCall({Map<String, dynamic>? dataBody});
  Future<List<CheckAndUpdateCheckingPointForFsrResponseModel>> getFsrCheckingPointDetailsApiCall({Map<String, dynamic>? dataBody,parameter});
  Future<FsrResponseModel> postfsrDetailsApiCall({Map<String, dynamic>? dataBody, parameters});
  Future<FSRDeleteRespnseModel> deletefsrDetailsApiCall({Map<String, dynamic>? dataBody, required String id});
  Future<FsrResponseModel> putfsrDetailsApiCall(
      {Map<String, dynamic>? dataBody, required String id});
  Future<CheckPointsResponseModel>postcheckPointStatusDetailsApiCall({Map<String, dynamic>? dataBody,});
  Future<LeaveAllocationResponseModel>getLeavesALLocationApiCall({Map<String, dynamic>? dataBody});
  Future<LeaveAllocationResponseModel>putLeavesAllocationApiCall({Map<String, dynamic>? dataBody,id});
  Future<SuperUsersResponseModel>getAgentDetailsApiCall({Map<String, dynamic>? dataBody,parameters} );
  Future<AgentsPostResponseModel> postAgentDetailwsApiCall({Map<String, dynamic>? dataBody, parameters});
  Future<AgentsPostResponseModel> putAgentDetailwsApiCall({Map<String, dynamic>? dataBody, parameters,required String id});
  Future<CustomerListResponseModel>getCustomerListApiCall({Map<String, dynamic>?dataBody, parameters});
  Future<PostCustomerListResponseModel> putCustomerListApiCall({Map<String, dynamic>?dataBody, parameters, String? id});
  Future<DeleteUserResponseModel> deleteCustomerListApiCall({Map<String, dynamic>?dataBody, parameters, String? id});
  Future<PostCustomerListResponseModel> postCustomerListApiCall({Map<String, dynamic>?dataBody, parameters});
  Future<LeadGetResponseModel> getLeadListApiCall({Map<String, dynamic>?dataBody, parameters});
  Future<List<LeadSourceTypeResponseModel>>getListLeadSourceTypeResponseModel({Map<String, dynamic>?dataBody,});
  Future<PostLeadSourceTypeResponseModel> postLeadStatusApiCall({Map<String, dynamic>?dataBody});
  Future<PostLeadListResponeModel> putLeadListApiCall({Map<String, dynamic>?dataBody, parameters, String? id});
  Future<LeadGetResponseModel> deleteLeadListApiCall({Map<String, dynamic>?dataBody, parameters, String? id});
  Future<PostLeadListResponeModel> postLeadListApiCall({Map<String, dynamic>?dataBody, parameters});
  Future<LeadStatusResponseModel> getLeadStatusApiCall({Map<String, dynamic>?dataBody});// Future<LeadPostResponseModel>postLeadListApiCall({Map<String, dynamic>?dataBody});
  // Future<LeadPostResponseModel>delLeadListApiCall({Map<String, dynamic>?dataBody, String? id});
  // Future<LeadPostResponseModel>putLeadListApiCall({Map<String, dynamic>?dataBody, String? id});
  Future<TodayTicketDataResponseModel>getTodayTicketDetailsApiCall({Map<String, dynamic>?dataBody});
  Future<ServiceCategoryResponseModel>getServiceCategoriesApiCall({Map<String, dynamic>? dataBody});
  Future<PostServiceCategoryResponseModel>postServiceCategoriesApiCall({required dioo.FormData dataBody});
  Future<PostServiceCategoryResponseModel>deleteServiceCategoriesApiCall({Map<String, dynamic>? dataBody, parameters});
  Future<SubServiceResponseModel>getSub_ServiceCategoriesApiCall({Map<String, dynamic>? dataBody,parameters});
  Future<SubServiceBySubServiceIdResponseModel> getSub_ServiceCategoriesByIdApiCall({Map<String, dynamic>? dataBody, parameters});
  Future<PostServiceCategoryResponseModel> PostSub_ServiceCategoriesByIdApiCall({required dioo.FormData dataBody});
  Future<PostSubServiceResponseModel>postSubServiceCategoriesApiCall({required dioo.FormData dataBody});
  Future<TmsResponseModel>getuserDetailsApiCall({Map<String, dynamic>? dataBody});
  Future<Uint8List> downloadTicketDataByUsername({Map<String, dynamic>? dataBody, String? id});
  Future<ExcelTicket> exportTicketDataByDate({Map<String, dynamic>? dataBody, parameter});
  Future<TicketResponseModel> putTicketDetailsApiCall({Map<String, dynamic>? dataBody});
  Future<TicketCountsResponseModel>getTicketCountsApiCall({Map<String, dynamic>? dataBody, parameter});
  // Future<Uint8List> exportTicketDataByDate({Map<String, dynamic>? dataBody, parameter});
  // Future<List<TMSResponseModel>>getuserDetailsApiCall({Map<String, dynamic>? dataBody});
  Future<TechnicianAttendanceResponseModel>getAttendanceApiCall({Map<String, dynamic>? dataBody , dynamic parameters});
  Future<AttendanceCountsReponseModel>getAttendanceCountApiCall({Map<String, dynamic>? dataBody, parameter});
  Future<PunchInOutResponseModel>postPunchInApiCall({Map<String, dynamic>? dataBody , dynamic parameters});
  Future<PunchInOutResponseModel>postPunchOutApiCall({Map<String, dynamic>? dataBody , dynamic parameters});
  Future<ExpensesResponseModel>getExpensesApiCall({Map<String, dynamic>? dataBody, parameters});
  // Future<List<ExpensesResponseModel>>getExpensesApiCall({Map<String, dynamic>?dataBody, parameters});
  Future<ServiceRequestResponseModel>getServiceRequestsApiCall({Map<String, dynamic>? dataBody, parameters});
  Future<TechnicianResponseModel>getTechnicianApiCall({Map<String, dynamic>? dataBody, parameters}) ;
  Future<AddTechnicianResponseModel> updateTechnicialPostApiCall({Map<String, dynamic>? dataBody, parameters,String? id});
  Future<TechnicianResponseModel>deleteTechnicianDetailsApiCall({Map<String, dynamic>? dataBody, parameters,String? id});
  Future<SalesResponseModel>getSalesDetailsApiCall({Map<String, dynamic>? dataBody, parameters});
  Future<AddSalesResponseModel>postAddSalesDetailsApiCall({Map<String, dynamic>? dataBody, parameters});
  Future<AddSalesResponseModel>updateAddSalesDetailsApiCall({Map<String, dynamic>? dataBody, parameters,String? id});
  Future<SalesResponseModel>deleteAddSalesDetailsApiCall({Map<String, dynamic>? dataBody, parameters, String? id});
  Future<AmcResponseModel>getAmcDetailsApiCall({Map<String, dynamic>?dataBody, parameter});
  Future<PostAmcResponseModel>updateAmcDetailsApiCall({Map<String, dynamic>?dataBody, String? id});
  Future<AmcDeleteResponseModel>deleteAmcDetailsApiCall({Map<String, dynamic>?dataBody,String? id});
  Future<AmcCountResponseModel>getAmcCountsApiCall({Map<String, dynamic>?dataBody, parameter});
  Future<PostAmcResponseModel>postAmcDetailsApiCall({Map<String, dynamic>?dataBody});
  Future<ServicesResponseModel> getAllservicesPricesAndDetails({Map<String, dynamic>?dataBody,parameter});
  Future<List<AttendanceResponseModel>>getAttendanceHistoryApiCall({Map<String, dynamic>?dataBody, parameters});
  Future<AmcDataCustomerWiseResponseModel>getAMCCustomerWiseDataApiCall({Map<String, dynamic>?dataBody,parameter});
  Future<List<AmcHistoryViewResponseModel>>getAmcHistoryData({Map<String, dynamic>?dataBody,required String id });
  Future<List<LeadHistoryResponseModel>>getLeadHistoryApiCall({Map<String,dynamic>?dataBody,required String id});
  Future<List<InteractionLeadsResponseModel>>getLeadInteractionApiCall({Map<String,dynamic>?dataBody,required parameters});
  Future<CustomerRatingResponseModel>getCustomerRatingApiCall({Map<String,dynamic>?dataBody});
  Future<UserLeavesDataResponseModel>getUserLeavesDataApiCall({Map<String,dynamic>?dataBody});
  Future<TechnicianAttendanceDataResponseModel>getTechnicianStatusCountsDataApiCall({Map<String,dynamic>?dataBody});
  Future<List<Map<String, dynamic>>> exportAttendancebyCall({
    Map<String, dynamic>? dataBody,
    required Map<String, dynamic> parameters,
    required String id
  });
}